name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        env:
          TIMEZONE: Asia/Tokyo
        with:
          feed_list: "https://jioneeu.github.io/feed"
          max_post_count: 3
          readme_path: './README.md'
